CREATE TABLE IF NOT EXISTS ingredients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    category TEXT,
    purchase_tier TEXT,
    canonical_unit TEXT,
    grams_per_cup REAL,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS unit_conversions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name TEXT,
    quantity_from REAL NOT NULL,
    unit_from TEXT NOT NULL,
    quantity_to REAL NOT NULL,
    unit_to TEXT NOT NULL,
    context TEXT NOT NULL,
    source_sheet TEXT,
    source_row INTEGER,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ingredient_aliases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_name TEXT NOT NULL,
    alias_name TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'manual',
    confidence REAL,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recipes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    category TEXT,
    base_servings REAL NOT NULL,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recipe_ingredients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id INTEGER NOT NULL,
    ingredient_id INTEGER NOT NULL,
    quantity REAL NOT NULL,
    unit TEXT NOT NULL,
    prep_notes TEXT,
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS recipe_steps (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id INTEGER NOT NULL,
    step_order INTEGER NOT NULL,
    instruction TEXT NOT NULL,
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('viewer', 'planner', 'admin')),
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS guest_access_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT,
    updated_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS retreats (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    start_date TEXT,
    end_date TEXT,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS menu_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retreat_id INTEGER NOT NULL,
    day_label TEXT NOT NULL,
    meal_label TEXT NOT NULL,
    recipe_id INTEGER NOT NULL,
    target_servings REAL NOT NULL,
    FOREIGN KEY (retreat_id) REFERENCES retreats(id) ON DELETE CASCADE,
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS inventory_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id INTEGER NOT NULL,
    quantity REAL NOT NULL,
    unit TEXT NOT NULL,
    source TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS vendors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS retreat_plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    start_date TEXT,
    day_count INTEGER NOT NULL,
    default_people REAL NOT NULL,
    plan_json TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shopping_lists (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retreat_id INTEGER,
    retreat_plan_id INTEGER REFERENCES retreat_plans(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    phase TEXT NOT NULL DEFAULT 'bulk',
    generation_config_json TEXT,
    status TEXT NOT NULL DEFAULT 'draft',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (retreat_id) REFERENCES retreats(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS shopping_list_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_list_id INTEGER NOT NULL,
    ingredient_id INTEGER NOT NULL,
    required_qty REAL NOT NULL,
    required_unit TEXT NOT NULL,
    in_stock_qty REAL,
    in_stock_unit TEXT,
    to_buy_qty REAL,
    to_buy_unit TEXT,
    ordered_qty REAL,
    ordered_unit TEXT,
    vendor_id INTEGER,
    owner TEXT,
    pickup_date TEXT,
    ordered INTEGER NOT NULL DEFAULT 0,
    ordered_at TEXT,
    received INTEGER NOT NULL DEFAULT 0,
    received_at TEXT,
    status TEXT NOT NULL DEFAULT 'open',
    notes TEXT,
    FOREIGN KEY (shopping_list_id) REFERENCES shopping_lists(id) ON DELETE CASCADE,
    FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON DELETE RESTRICT,
    FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS shopping_list_item_sources (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_list_item_id INTEGER NOT NULL,
    retreat_plan_id INTEGER REFERENCES retreat_plans(id) ON DELETE SET NULL,
    retreat_plan_name TEXT NOT NULL,
    dish_name TEXT,
    required_qty REAL NOT NULL,
    required_unit TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (shopping_list_item_id) REFERENCES shopping_list_items(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS shopping_list_item_vendor_allocations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_list_item_id INTEGER NOT NULL,
    vendor_id INTEGER,
    allocated_qty REAL NOT NULL DEFAULT 0,
    allocated_unit TEXT NOT NULL,
    ordered INTEGER NOT NULL DEFAULT 0,
    ordered_at TEXT,
    received INTEGER NOT NULL DEFAULT 0,
    received_at TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (shopping_list_item_id) REFERENCES shopping_list_items(id) ON DELETE CASCADE,
    FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS shopping_pickup_lists (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_list_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    vendor_id INTEGER,
    assignee TEXT,
    pickup_date TEXT,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (shopping_list_id) REFERENCES shopping_lists(id) ON DELETE CASCADE,
    FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS shopping_pickup_list_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_pickup_list_id INTEGER NOT NULL,
    shopping_list_item_id INTEGER REFERENCES shopping_list_items(id) ON DELETE SET NULL,
    source_ingredient_id INTEGER NOT NULL,
    source_canonical_unit TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (shopping_pickup_list_id) REFERENCES shopping_pickup_lists(id) ON DELETE CASCADE,
    FOREIGN KEY (source_ingredient_id) REFERENCES ingredients(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_recipe_ingredients_recipe_id ON recipe_ingredients(recipe_id);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_id ON auth_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires_at ON auth_sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_guest_access_sessions_scope ON guest_access_sessions(scope);
CREATE INDEX IF NOT EXISTS idx_guest_access_sessions_expires_at ON guest_access_sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_menu_items_retreat_id ON menu_items(retreat_id);
CREATE INDEX IF NOT EXISTS idx_inventory_items_ingredient_id ON inventory_items(ingredient_id);
CREATE INDEX IF NOT EXISTS idx_shopping_items_list_id ON shopping_list_items(shopping_list_id);
CREATE INDEX IF NOT EXISTS idx_shopping_items_vendor_id ON shopping_list_items(vendor_id);
CREATE INDEX IF NOT EXISTS idx_shopping_item_sources_item_id ON shopping_list_item_sources(shopping_list_item_id);
CREATE INDEX IF NOT EXISTS idx_shopping_item_sources_plan_id ON shopping_list_item_sources(retreat_plan_id);
CREATE INDEX IF NOT EXISTS idx_shopping_item_vendor_allocations_item_id ON shopping_list_item_vendor_allocations(shopping_list_item_id);
CREATE INDEX IF NOT EXISTS idx_shopping_item_vendor_allocations_vendor_id ON shopping_list_item_vendor_allocations(vendor_id);
CREATE INDEX IF NOT EXISTS idx_shopping_pickup_lists_list_id ON shopping_pickup_lists(shopping_list_id);
CREATE INDEX IF NOT EXISTS idx_shopping_pickup_lists_vendor_id ON shopping_pickup_lists(vendor_id);
CREATE INDEX IF NOT EXISTS idx_shopping_pickup_list_items_pickup_list_id ON shopping_pickup_list_items(shopping_pickup_list_id);
CREATE INDEX IF NOT EXISTS idx_shopping_pickup_list_items_item_id ON shopping_pickup_list_items(shopping_list_item_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_shopping_pickup_list_items_unique_source ON shopping_pickup_list_items(
    shopping_pickup_list_id,
    source_ingredient_id,
    source_canonical_unit
);
CREATE INDEX IF NOT EXISTS idx_unit_conversions_item_name ON unit_conversions(item_name);
CREATE INDEX IF NOT EXISTS idx_unit_conversions_context ON unit_conversions(context);
CREATE INDEX IF NOT EXISTS idx_ingredient_aliases_ingredient_name ON ingredient_aliases(ingredient_name);
CREATE INDEX IF NOT EXISTS idx_ingredient_aliases_alias_name ON ingredient_aliases(alias_name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ingredient_aliases_unique ON ingredient_aliases(ingredient_name, alias_name, source);

CREATE INDEX IF NOT EXISTS idx_retreat_plans_updated_at ON retreat_plans(updated_at);

CREATE TABLE IF NOT EXISTS service_snapshots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retreat_name TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    retreat_plan_id INTEGER REFERENCES retreat_plans(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_service_snapshots_created_at ON service_snapshots(created_at);
CREATE INDEX IF NOT EXISTS idx_service_snapshots_retreat_plan_id ON service_snapshots(retreat_plan_id);

CREATE TABLE IF NOT EXISTS standalone_inventory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name TEXT NOT NULL,
    barcode TEXT,
    quantity REAL NOT NULL DEFAULT 0,
    unit TEXT,
    category TEXT,
    location TEXT,
    image_url TEXT,
    notes TEXT,
    order_url TEXT,
    import_source TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_standalone_inventory_category ON standalone_inventory(category);
CREATE INDEX IF NOT EXISTS idx_standalone_inventory_barcode ON standalone_inventory(barcode);

CREATE TABLE IF NOT EXISTS standalone_inventory_barcodes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id INTEGER NOT NULL REFERENCES standalone_inventory(id) ON DELETE CASCADE,
    barcode TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_standalone_inventory_barcodes_item_id
ON standalone_inventory_barcodes(inventory_item_id);

CREATE TABLE IF NOT EXISTS inventory_product_catalog (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    barcode TEXT NOT NULL,
    product_name TEXT,
    brand TEXT,
    category TEXT,
    unit TEXT,
    image_url TEXT,
    product_url TEXT,
    source_sku TEXT,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(source, barcode)
);

CREATE INDEX IF NOT EXISTS idx_inventory_product_catalog_barcode ON inventory_product_catalog(barcode);
CREATE INDEX IF NOT EXISTS idx_inventory_product_catalog_source ON inventory_product_catalog(source);
CREATE INDEX IF NOT EXISTS idx_inventory_product_catalog_name ON inventory_product_catalog(product_name);

CREATE TABLE IF NOT EXISTS inventory_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain TEXT NOT NULL CHECK (domain IN ('FOOD', 'NON_FOOD')),
    source_type TEXT CHECK (source_type IN ('SHOPPING_LIST', 'NON_FOOD_PLAN', 'MANUAL', 'LEGACY')),
    source_id INTEGER,
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'ORDERED', 'PARTIAL', 'RECEIVED')),
    workflow_stage TEXT NOT NULL DEFAULT 'PLANNING' CHECK (workflow_stage IN ('PLANNING', 'PURCHASING', 'RECEIVING', 'COMPLETE')),
    supplier_name TEXT,
    notes TEXT,
    created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    ordered_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    ordered_at TEXT,
    received_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    received_at TEXT,
    put_away_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    put_away_at TEXT,
    completed_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    completed_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_inventory_orders_domain ON inventory_orders(domain);
CREATE INDEX IF NOT EXISTS idx_inventory_orders_status ON inventory_orders(status);
CREATE INDEX IF NOT EXISTS idx_inventory_orders_workflow_stage ON inventory_orders(workflow_stage);
CREATE INDEX IF NOT EXISTS idx_inventory_orders_source ON inventory_orders(source_type, source_id);

CREATE TABLE IF NOT EXISTS inventory_order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES inventory_orders(id) ON DELETE CASCADE,
    item_type TEXT NOT NULL CHECK (item_type IN ('INGREDIENT', 'STANDALONE_INVENTORY')),
    item_id INTEGER NOT NULL,
    item_name_snapshot TEXT NOT NULL,
    category_snapshot TEXT,
    unit_snapshot TEXT NOT NULL DEFAULT 'each',
    current_quantity_snapshot REAL NOT NULL DEFAULT 0,
    required_quantity REAL NOT NULL DEFAULT 0 CHECK (required_quantity >= 0),
    ordered_quantity REAL NOT NULL DEFAULT 0 CHECK (ordered_quantity >= 0),
    received_quantity REAL NOT NULL DEFAULT 0 CHECK (received_quantity >= 0),
    applied_quantity REAL NOT NULL DEFAULT 0 CHECK (applied_quantity >= 0),
    purchase_unit TEXT NOT NULL DEFAULT 'unit',
    units_per_purchase REAL NOT NULL DEFAULT 1 CHECK (units_per_purchase > 0),
    draft_purchase_unit TEXT NOT NULL DEFAULT 'unit',
    draft_units_per_purchase REAL NOT NULL DEFAULT 1 CHECK (draft_units_per_purchase > 0),
    draft_ordered_purchase_quantity REAL NOT NULL DEFAULT 0 CHECK (draft_ordered_purchase_quantity >= 0),
    ordered_purchase_quantity REAL NOT NULL DEFAULT 0 CHECK (ordered_purchase_quantity >= 0),
    received_purchase_quantity REAL NOT NULL DEFAULT 0 CHECK (received_purchase_quantity >= 0),
    source_shopping_list_item_id INTEGER REFERENCES shopping_list_items(id) ON DELETE SET NULL,
    order_url_snapshot TEXT,
    order_url_override TEXT,
    notes TEXT,
    ordered_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    ordered_at TEXT,
    received_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    received_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (received_quantity <= ordered_quantity OR ordered_quantity = 0),
    CHECK (received_purchase_quantity <= ordered_purchase_quantity OR ordered_purchase_quantity = 0),
    CHECK (applied_quantity <= received_quantity)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_inventory_order_items_unique
ON inventory_order_items(order_id, item_type, item_id, source_shopping_list_item_id);

CREATE INDEX IF NOT EXISTS idx_inventory_order_items_order_id
ON inventory_order_items(order_id);

CREATE INDEX IF NOT EXISTS idx_inventory_order_items_item_ref
ON inventory_order_items(item_type, item_id);

CREATE INDEX IF NOT EXISTS idx_inventory_order_items_source_shopping
ON inventory_order_items(source_shopping_list_item_id);

CREATE TABLE IF NOT EXISTS inventory_order_item_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES inventory_orders(id) ON DELETE CASCADE,
    order_item_id INTEGER REFERENCES inventory_order_items(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL CHECK (event_type IN ('CREATE', 'UPDATE', 'ORDERED', 'RECEIVE', 'PUT_AWAY', 'TAKE_OUT', 'ADJUSTMENT')),
    quantity REAL,
    purchase_quantity REAL,
    location TEXT,
    notes TEXT,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_inventory_order_item_events_order_id
ON inventory_order_item_events(order_id);

CREATE INDEX IF NOT EXISTS idx_inventory_order_item_events_order_item_id
ON inventory_order_item_events(order_item_id);

CREATE TABLE IF NOT EXISTS inventory_movements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain TEXT NOT NULL CHECK (domain IN ('FOOD', 'NON_FOOD')),
    item_type TEXT NOT NULL CHECK (item_type IN ('INGREDIENT', 'STANDALONE_INVENTORY')),
    item_id INTEGER NOT NULL,
    order_id INTEGER REFERENCES inventory_orders(id) ON DELETE SET NULL,
    order_item_id INTEGER REFERENCES inventory_order_items(id) ON DELETE SET NULL,
    movement_type TEXT NOT NULL CHECK (movement_type IN ('IN', 'OUT', 'ADJUSTMENT')),
    quantity_delta REAL NOT NULL,
    unit TEXT,
    location TEXT,
    reason TEXT,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    actor_name TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_inventory_movements_created_at
ON inventory_movements(created_at);

CREATE INDEX IF NOT EXISTS idx_inventory_movements_item_ref
ON inventory_movements(item_type, item_id);

CREATE INDEX IF NOT EXISTS idx_inventory_movements_order_id
ON inventory_movements(order_id);

CREATE TABLE IF NOT EXISTS retreat_inventory_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    tracking_mode TEXT NOT NULL CHECK (tracking_mode IN ('ITEM', 'CATEGORY')),
    image_url TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TEXT
);

CREATE TABLE IF NOT EXISTS retreat_inventory_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    barcode TEXT NOT NULL UNIQUE,
    category_id INTEGER NOT NULL REFERENCES retreat_inventory_categories(id) ON DELETE RESTRICT,
    shelf_location TEXT,
    unit TEXT NOT NULL DEFAULT 'each',
    purchase_url TEXT,
    brand TEXT,
    description TEXT,
    image_url TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TEXT
);

CREATE TABLE IF NOT EXISTS retreat_inventory_locations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TEXT
);

CREATE TABLE IF NOT EXISTS retreat_inventory_item_locations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL REFERENCES retreat_inventory_items(id) ON DELETE CASCADE,
    location_id INTEGER NOT NULL REFERENCES retreat_inventory_locations(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(item_id, location_id)
);

CREATE TABLE IF NOT EXISTS retreat_inventory_levels (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER REFERENCES retreat_inventory_items(id) ON DELETE CASCADE,
    category_id INTEGER REFERENCES retreat_inventory_categories(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL DEFAULT 0,
    min_threshold INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (item_id IS NOT NULL AND category_id IS NULL)
        OR
        (item_id IS NULL AND category_id IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_retreat_inventory_levels_item_unique
ON retreat_inventory_levels(item_id) WHERE item_id IS NOT NULL AND category_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_retreat_inventory_levels_category_unique
ON retreat_inventory_levels(category_id) WHERE category_id IS NOT NULL AND item_id IS NULL;

CREATE TABLE IF NOT EXISTS retreat_inventory_transactions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('ITEM', 'CATEGORY')),
    entity_id INTEGER NOT NULL,
    transaction_type TEXT NOT NULL CHECK (transaction_type IN ('IN', 'OUT', 'ADJUSTMENT')),
    quantity INTEGER NOT NULL,
    reason TEXT,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    barcode TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS retreat_inventory_retreats (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    start_date TEXT,
    end_date TEXT,
    guest_count INTEGER,
    status TEXT NOT NULL DEFAULT 'PLANNED' CHECK (status IN ('PLANNED', 'COMPLETED')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TEXT
);

CREATE TABLE IF NOT EXISTS retreat_inventory_retreat_requirements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retreat_id INTEGER NOT NULL REFERENCES retreat_inventory_retreats(id) ON DELETE CASCADE,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('ITEM', 'CATEGORY')),
    entity_id INTEGER NOT NULL,
    required_quantity INTEGER NOT NULL CHECK (required_quantity >= 0),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_retreat_inventory_requirements_unique
ON retreat_inventory_retreat_requirements(retreat_id, entity_type, entity_id);

CREATE TABLE IF NOT EXISTS retreat_inventory_purchase_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name TEXT,
    status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'ORDERED', 'PARTIAL', 'RECEIVED')),
    expected_date TEXT,
    notes TEXT,
    created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TEXT
);

CREATE TABLE IF NOT EXISTS retreat_inventory_purchase_order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id INTEGER NOT NULL REFERENCES retreat_inventory_purchase_orders(id) ON DELETE CASCADE,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('ITEM', 'CATEGORY')),
    entity_id INTEGER NOT NULL,
    ordered_quantity INTEGER NOT NULL CHECK (ordered_quantity >= 0),
    received_quantity INTEGER NOT NULL DEFAULT 0 CHECK (received_quantity >= 0),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_retreat_inventory_po_items_unique
ON retreat_inventory_purchase_order_items(purchase_order_id, entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_retreat_inventory_items_category_id ON retreat_inventory_items(category_id);
CREATE INDEX IF NOT EXISTS idx_retreat_inventory_items_barcode ON retreat_inventory_items(barcode);
CREATE INDEX IF NOT EXISTS idx_retreat_inventory_locations_name ON retreat_inventory_locations(name);
CREATE INDEX IF NOT EXISTS idx_retreat_inventory_item_locations_item_id ON retreat_inventory_item_locations(item_id);
CREATE INDEX IF NOT EXISTS idx_retreat_inventory_item_locations_location_id ON retreat_inventory_item_locations(location_id);
CREATE INDEX IF NOT EXISTS idx_retreat_inventory_transactions_created_at ON retreat_inventory_transactions(created_at);
CREATE INDEX IF NOT EXISTS idx_retreat_inventory_transactions_entity ON retreat_inventory_transactions(entity_type, entity_id);
